# GoReleaser configuration - macOS only
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: memo
    binary: memo
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

# Homebrew
brews:
  - name: memo
    repository:
      owner: YoungY620
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/YoungY620/memo"
    description: "AI-powered codebase memory for coding agents"
    license: "MIT"
    install: |
      bin.install "memo"
    test: |
      system "#{bin}/memo", "--version"

release:
  github:
    owner: YoungY620
    name: memo
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
